let
    Source = Csv.Document(File.Contents("C:\Users\judith.calvo\OneDrive - Community Solutions\_aUCB Data Analytics Bootcamp Class\Final Project Folder\Archived CSV\shortcans.csv"),[Delimiter=",", Columns=43, Encoding=1252, QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"assess_draft_final_Value", type text}, {"assess_type", Int64.Type}, {"assess_type_Value", type text}, {"cans_assess_date", type date}, {"cans_care_develop", Int64.Type}, {"cans_care_involvement", Int64.Type}, {"cans_care_know", Int64.Type}, {"cans_care_mental", Int64.Type}, {"cans_care_organization", Int64.Type}, {"cans_care_phy_med", Int64.Type}, {"cans_care_physical", Int64.Type}, {"cans_care_resources", Int64.Type}, {"cans_care_safety", Int64.Type}, {"cans_care_stability", Int64.Type}, {"cans_care_substance", Int64.Type}, {"cans_care_supervision", Int64.Type}, {"cans_ldf_sch_achieve", type text}, {"cans_ldf_sch_attend", type text}, {"cans_ldf_sch_behavior", type text}, {"cans_ldf_social_func", Int64.Type}, {"cans_yb_anger", Int64.Type}, {"cans_yb_conduct", Int64.Type}, {"cans_yb_depression", Int64.Type}, {"cans_yb_impluse", Int64.Type}, {"cans_yb_opposition", Int64.Type}, {"cans_yb_pschosis", Int64.Type}, {"cans_yb_substance", Int64.Type}, {"cans_yb_trauma", Int64.Type}, {"cans_ys_family", Int64.Type}, {"cans_ys_interpersonal", Int64.Type}, {"cans_ys_natural_supp", Int64.Type}, {"cans_ys_optimism", Int64.Type}, {"cans_ys_relationship", Int64.Type}, {"cans_ys_resiliency", Int64.Type}, {"cans_ys_spirit", Int64.Type}, {"cans_ys_talent", Int64.Type}, {"cans_ys_vocation", type text}, {"cans_ys_resource", Int64.Type}, {"PATID", Int64.Type}, {"EPISODE_NUMBER", Int64.Type}, {"preadmit_admission_date", type date}, {"date_of_discharge", type date}, {"program_code", type text}})
in
    #"Changed Type"